using System;
using System.Runtime.InteropServices;

namespace System.Runtime.CompilerServices
{
    /// <summary>Specifies parameters that control the strictness of the code generated by the common language runtime's just-in-time (JIT) compiler.</summary>
    [Serializable]
    [FlagsAttribute()]
    [ComVisibleAttribute(true)]
    public enum CompilationRelaxations : int
    {
        /// <summary>Marks an assembly as not requiring string-literal interning.</summary>
        NoStringInterning = 8
    }
}
