using System;

namespace System.Runtime.CompilerServices
{
    /// <summary>Allows you to determine whether a method is a state machine method.</summary>
    [Serializable]
    [AttributeUsageAttribute(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public class StateMachineAttribute : Attribute
    {
    
        /// <summary>Returns the type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</summary><returns>Gets the type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</returns>
        public Type StateMachineType
        {
            get { throw new NotImplementedException(); }
        }
    
    
        /// <summary>Initializes a new instance of the <see cref="T:System.Runtime.CompilerServices.StateMachineAttribute" /> class.</summary><param name="stateMachineType">The type object for the underlying state machine type that was generated by the compiler to implement the state machine method.</param>
        public StateMachineAttribute(Type stateMachineType)
        {
             throw new NotImplementedException();
        }
        
        
    }
}
